# Ruff configuration (opinionated defaults)
[tool.ruff]
select = [
  "E",     # pycodestyle errors
  "W",     # pycodestyle warnings
  "F",     # pyflakes errors
  "PL",    # pylint
  "I",     # isort
  "FAST",  # FastAPI
  "ASYNC", # flake8-async
  "B",     # flake8-bugbear
  "INP",   # flake8-no-pep420
  "PT",    # flake8-pytest-style
  "Q",     # flake8-quotes
  "SIM",   # flake8-simplify
  "C90",   # mccabe
  "FURB",  # refurb
  "RUF",   # ruff
  "TRY"    # tryceratops
]

[tool.ruff.per-file-ignores]
"{tests}/**/*" = ["S"]
